local L                         = Scorpio("BagView")._Locale("zhCN")
if not L then return end

L["Trace"]                      = "跟踪"
L["Debug"]                      = "调试"
L["Info"]                       = "信息"
L["Warn"]                       = "警告"
L["Error"]                      = "错误"
L["Fatal"]                      = "致命"

L["set the log level of the bag view"] = "修改BagView的日志等级"
L["BagView's log level is turn to %s"] = "BagView的日志级别调整为 - %s"

L["Open View Rule Manager"]     = "打开视图规则编辑器"
L["Auto Sell"]                  = "自动贩卖"
L["Auto Repair"]                = "自动修理"
L["Enable"]                     = "启用"
L["Check Reputation"]           = "检查NPC声望"

L["Bag View Rule Manager"]      = "视图规则编辑器"
L["Please input the new name"]  = "请输入新名字"
L["Please input the replace name"] = "请输入替换用名字"

L["Views"]                      = "视图集合"
L["Rename"]                     = "重命名"
L["Delete"]                     = "删除"
L["Add View"]                   = "添加视图"
L["Containers"]                 = "容器集合"
L["Container"]                  = "容器"
L["Add Container"]              = "添加容器"
L["Rules"]                      = "规则集合"
L["Add Rules"]                  = "添加规则集合"
L["Click to set"]               = "点击来设置"
L["Rule List"]                  = "规则列表"
L["Add Rule"]                   = "添加规则"
L["Item List - drag item here to add"] = "物品列表 - 拖拽物品进入来添加"
L["[AutoRepair] No enough money to repair."] = "【自动修理] 没有足够用于修理的钱。"
L["[AutoRepair] Cost [Guild] %s."] = "【自动修理】消耗【工会】 %s"
L["[AutoRepair] Cost %s."]      = "【自动修理】消耗 %s"
L["[AutoSell] Item List:"]      = "【自动贩卖】 物品列表："
L["[AutoSell] Total : %s."]     = "[自动贩卖】 总计收益： %s"
L["[AutoSell] Buy back item if you don't want auto sell it."] = "[自动贩卖】 买回不想自动贩卖的物品，之后不会再次被贩卖"
L["[AutoSell] Alt+Right-Click to mark item as auto sell."] = "[自动贩卖】 使用Alt+右键来自动贩卖某物品"

L["[NOT]"]                      = "[非]"
L["Default"]                    = "默认"
L["All-In-One"]                 = "整合"
L[" And "]                      = " 并且 "
L["Reagent"]                    = "材料"
L["Drag item to the right panel"] = "拖拽物品到右侧的面板"

L["InItemList"]                 = "物品列表中"
L["Any"]                        = "任意"
L["Backpack"]                   = "背包"
L["Container1"]                 = "扩展背包1"
L["Container2"]                 = "扩展背包2"
L["Container3"]                 = "扩展背包3"
L["Container4"]                 = "扩展背包4"
L["Bank"]                       = "银行"
L["ReagentBank"]                = "材料银行"
L["BankBag1"]                   = "银行扩展背包1"
L["BankBag2"]                   = "银行扩展背包2"
L["BankBag3"]                   = "银行扩展背包3"
L["BankBag4"]                   = "银行扩展背包4"
L["BankBag5"]                   = "银行扩展背包5"
L["BankBag6"]                   = "银行扩展背包6"
L["BankBag7"]                   = "银行扩展背包7"
L["HasItem"]                    = "含有物品"
L["Readable"]                   = "可读"
L["Lootable"]                   = "可拾取"
L["HasNoValue"]                 = "无价值"
L["IsQuestItem"]                = "任务"
L["IsEquipItem"]                = "装备"
L["IsStackableItem"]            = "可堆叠"
L["IsUsableItem"]               = "可使用"
L["IsNewItem"]                  = "新物品"
L["IsEquipSet"]                 = "装备配置方案中"

L["Lock Container Frame"]       = "锁定背包面板"
L["Show the view manager"]      = "显示视图管理器"
L["Container View Rule Manager"]= "背包视图规则管理器"
L["Container"]                  = "容器"
L["Rule"]                       = "规则"
L["Please input the container view's name"] = "请输入背包视图的名称"
L["Do you want delete the container view?"] = "你确定删除该背包视图？"
L["Do you want delete the container?"]      = "你确定删除该容器？"
L["Do you want delete the contianer rule?"] = "你确定删除该容器规则？"

L["Tooltip Filter(Use ';' to seperate)"] = "鼠标提示信息过滤(使用';'号来间隔)"


L[100000]                       = "物品槽中有物品存在，并且该物品属于物品列表(选择视图来显示物品列表面板，拖拽物品进入来添加，点击物品链接来移除)"

L[100001]                       = "无检查，你应当仅用于视图的最后一个容器"
L[100002]                       = "物品槽在出生背包中"
L[100003]                       = "物品槽在扩展背包1中(从右往左数)"
L[100004]                       = "物品槽在扩展背包2中(从右往左数)"
L[100005]                       = "物品槽在扩展背包3中(从右往左数)"
L[100006]                       = "物品槽在扩展背包4中(从右往左数)"

L[110001]                       = "物品槽在银行中"
L[110002]                       = "物品槽在材料银行中"
L[110003]                       = "物品槽在银行扩展背包1中"
L[110004]                       = "物品槽在银行扩展背包2中"
L[110005]                       = "物品槽在银行扩展背包3中"
L[110006]                       = "物品槽在银行扩展背包4中"
L[110007]                       = "物品槽在银行扩展背包5中"
L[110008]                       = "物品槽在银行扩展背包6中"
L[110009]                       = "物品槽在银行扩展背包7中"

L[100007]                       = "物品槽中有物品存在"
L[100008]                       = "物品槽中有物品存在，并且该物品可读，比如书籍或者卷轴"
L[100009]                       = "物品槽中有物品存在，并且该物品是可以被拾取的容器"
L[100010]                       = "物品槽中有物品存在，并且该物品没有价值(不可销售)"
L[100011]                       = "物品槽中有物品存在，并且该物品是任务物品"
L[100012]                       = "物品槽中有物品存在，并且该物品是装备物品"
L[100013]                       = "物品槽中有物品存在，并且该物品是可堆叠的"
L[100014]                       = "物品槽中有物品存在，并且该物品是被右键使用的"
L[100015]                       = "物品槽中有物品存在，并且该物品是新加入的"
L[100016]                       = "物品槽中有物品存在，并且该物品属于某个装备配置方案"
L[100017]                       = "物品槽中有物品存在，并且该物品具有未获取的外观"
L[100018]                       = "物品槽中有物品存在，并且该物品未绑定"
L[100019]                       = "物品槽中有物品存在，并且该物品是神器能量"


L[200001]                       = "物品槽中有物品存在，并且该物品是粗糙的(灰色)"
L[200002]                       = "物品槽中有物品存在，并且该物品是普通的(白色)"
L[200003]                       = "物品槽中有物品存在，并且该物品是优秀的(绿色)"
L[200004]                       = "物品槽中有物品存在，并且该物品是精良的(蓝色)"
L[200005]                       = "物品槽中有物品存在，并且该物品是史诗的(紫色)"
L[200006]                       = "物品槽中有物品存在，并且该物品是传说的(橙色)"
L[200007]                       = "物品槽中有物品存在，并且该物品是神器的(暗金色)"
L[200008]                       = "物品槽中有物品存在，并且该物品是传家宝(淡金色)"
L[200009]                       = "物品槽中有物品存在，并且该物品是魔兽徽章的(淡金色)"

L[300000]                       = "物品槽中有物品存在，并且该物品的类型是 - "
L[300001]                       = "物品槽中有物品存在，并且该物品的子类型是 - "


