local L                         = Scorpio("BagView")._Locale("zhTW")
if not L then return end

L["Trace"]                      = "跟踪"
L["Debug"]                      = "調試"
L["Info"]                       = "信息"
L["Warn"]                       = "警告"
L["Error"]                      = "錯誤"
L["Fatal"]                      = "致命"

L["set the log level of the bag view"] = "修改BagView的日誌等級"
L["BagView's log level is turn to %s"] = "BagView的日誌級別調整為 - %s"

L["Open View Rule Manager"]     = "打開視圖規則編輯器"
L["Auto Sell"]                  = "自動販賣"
L["Auto Repair"]                = "自動修理"
L["Enable"]                     = "啟用"
L["Check Reputation"]           = "檢查NPC聲望"
L["Item Skin"]                  = "按鈕皮膚"
L["Container Skin"]             = "背包皮膚"

L["Bag View Rule Manager"]      = "視圖規則編輯器"
L["Please input the new name"]  = "請輸入新名字"
L["Please input the replace name"] = "請輸入替換用名字"

L["Views"]                      = "視圖集合"
L["Rename"]                     = "重命名"
L["Delete"]                     = "刪除"
L["Up"]                         = "上移"
L["Down"]                       = "下移"
L["Add View"]                   = "添加視圖"
L["Containers"]                 = "容器集合"
L["Container"]                  = "容器"
L["Add Container"]              = "添加容器"
L["Rules"]                      = "規則集合"
L["Add Rules"]                  = "添加規則集合"
L["Click to set"]               = "點擊來設置"
L["Rule List"]                  = "規則列表"
L["Add Rule"]                   = "添加規則"
L["Item List - drag item here to add"] = "物品列表 - 拖拽物品進入來添加"
L["[AutoRepair] No enough money to repair."] = "【自動修理] 沒有足夠用於修理的錢。"
L["[AutoRepair] Cost [Guild] %s."] = "【自動修理】消耗【工會】 %s"
L["[AutoRepair] Cost %s."]      = "【自動修理】消耗 %s"
L["[AutoSell] Item List:"]      = "【自動販賣】 物品列表："
L["[AutoSell] Total : %s."]     = "[自動販賣】 總計收益： %s"
L["[AutoSell] Buy back item if you don't want auto sell it."] = "[自動販賣】 買回不想自動販賣的物品，之後不會再次被販賣"
L["[AutoSell] Alt+Right-Click to mark item as auto sell."] = "[自動販賣】 使用Alt+右鍵來自動販賣某物品"

L["[NOT]"]                      = "[非]"
L["Default"]                    = "默認"
L["All-In-One"]                 = "整合"
L[" And "]                      = " 並且 "
L["Reagent"]                    = "材料"
L["Drag item to the right panel"] = "拖拽物品到右側的面板"

L["InItemList"]                 = "物品列表中"
L["Any"]                        = "任意"
L["Backpack"]                   = "背包"
L["Container1"]                 = "擴展背包1"
L["Container2"]                 = "擴展背包2"
L["Container3"]                 = "擴展背包3"
L["Container4"]                 = "擴展背包4"
L["Bank"]                       = "銀行"
L["ReagentBank"]                = "材料銀行"
L["BankBag1"]                   = "銀行擴展背包1"
L["BankBag2"]                   = "銀行擴展背包2"
L["BankBag3"]                   = "銀行擴展背包3"
L["BankBag4"]                   = "銀行擴展背包4"
L["BankBag5"]                   = "銀行擴展背包5"
L["BankBag6"]                   = "銀行擴展背包6"
L["BankBag7"]                   = "銀行擴展背包7"
L["HasItem"]                    = "含有物品"
L["Readable"]                   = "可讀"
L["Lootable"]                   = "可拾取"
L["HasNoValue"]                 = "無價值"
L["IsQuestItem"]                = "任務"
L["IsEquipItem"]                = "裝備"
L["IsStackableItem"]            = "可堆疊"
L["IsUsableItem"]               = "可使用"
L["IsNewItem"]                  = "新物品"
L["IsEquipSet"]                 = "裝備配置方案中"

L["Lock Container Frame"]       = "鎖定背包面板"
L["Show the view manager"]      = "顯示視圖管理器"
L["Container View Rule Manager"]= "背包視圖規則管理器"
L["Container"]                  = "容器"
L["Rule"]                       = "規則"
L["Please input the container view's name"] = "請輸入背包視圖的名稱"
L["Do you want delete the container view?"] = "你確定刪除該背包視圖？"
L["Do you want delete the container?"]      = "你確定刪除該容器？"
L["Do you want delete the contianer rule?"] = "你確定刪除該容器規則？"

L["Tooltip Filter(Use ';' to seperate)"] = "鼠標提示信息過濾(使用';'號來間隔)"


L[100000]                       = "物品槽中有物品存在，並且該物品屬於物品列表(選擇視圖來顯示物品列表面板，拖拽物品進入來添加，點擊物品鏈接來移除)"

L[100001]                       = "無檢查，你應當僅用於視圖的最後一個容器"
L[100002]                       = "物品槽在出生背包中"
L[100003]                       = "物品槽在擴展背包1中(從右往左數)"
L[100004]                       = "物品槽在擴展背包2中(從右往左數)"
L[100005]                       = "物品槽在擴展背包3中(從右往左數)"
L[100006]                       = "物品槽在擴展背包4中(從右往左數)"

L[110001]                       = "物品槽在銀行中"
L[110002]                       = "物品槽在材料銀行中"
L[110003]                       = "物品槽在銀行擴展背包1中"
L[110004]                       = "物品槽在銀行擴展背包2中"
L[110005]                       = "物品槽在銀行擴展背包3中"
L[110006]                       = "物品槽在銀行擴展背包4中"
L[110007]                       = "物品槽在銀行擴展背包5中"
L[110008]                       = "物品槽在銀行擴展背包6中"
L[110009]                       = "物品槽在銀行擴展背包7中"

L[100007]                       = "物品槽中有物品存在"
L[100008]                       = "物品槽中有物品存在，並且該物品可讀，比如書籍或者捲軸"
L[100009]                       = "物品槽中有物品存在，並且該物品是可以被拾取的容器"
L[100010]                       = "物品槽中有物品存在，並且該物品沒有價值(不可銷售)"
L[100011]                       = "物品槽中有物品存在，並且該物品是任務物品"
L[100012]                       = "物品槽中有物品存在，並且該物品是裝備物品"
L[100013]                       = "物品槽中有物品存在，並且該物品是可堆疊的"
L[100014]                       = "物品槽中有物品存在，並且該物品是被右鍵使用的"
L[100015]                       = "物品槽中有物品存在，並且該物品是新加入的"
L[100016]                       = "物品槽中有物品存在，並且該物品屬於某個裝備配置方案"
L[100017]                       = "物品槽中有物品存在，並且該物品具有未獲取的外觀"
L[100018]                       = "物品槽中有物品存在，並且該物品未綁定"
L[100019]                       = "物品槽中有物品存在，並且該物品是神器能量"

L[200001]                       = "物品槽中有物品存在，並且該物品是粗糙的(灰色)"
L[200002]                       = "物品槽中有物品存在，並且該物品是普通的(白色)"
L[200003]                       = "物品槽中有物品存在，並且該物品是優秀的(綠色)"
L[200004]                       = "物品槽中有物品存在，並且該物品是精良的(藍色)"
L[200005]                       = "物品槽中有物品存在，並且該物品是史詩的(紫色)"
L[200006]                       = "物品槽中有物品存在，並且該物品是傳說的(橙色)"
L[200007]                       = "物品槽中有物品存在，並且該物品是神器的(暗金色)"
L[200008]                       = "物品槽中有物品存在，並且該物品是傳家寶(淡金色)"
L[200009]                       = "物品槽中有物品存在，並且該物品是魔獸徽章的(淡金色)"

L[300000]                       = "物品槽中有物品存在，並且該物品的類型是 - "
L[300001]                       = "物品槽中有物品存在，並且該物品的子類型是 - "